version: '1.0'
name: masterpublish
displayName: 生成React并发布
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
  pr:
    branches:
      precise:
        - master
stages:
  - name: stage-06a2c72b
    displayName: 构建Node
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - cd ./wujiErp.React && yarn && yarn build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./wujiErp.React/build
        caches:
          - ~/.npm
          - ~/.yarn
        strategy:
          retry: '1'
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: wuji
        strategy:
          retry: '0'
        dependsOn: build_nodejs
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: wuji
        version: 1.0.0.0
        autoIncrement: true
        notify: []
        strategy:
          retry: '0'
        dependsOn: publish_general_artifacts
strategy:
  blocking: false
permissions:
  - role: admin
    members: []
